Avoid setting XCL_EMULATION_MODE to 'true'
Simluation was failing with the following error because internally we set the environment to 'true'. This is no longer supported on Xilinx SDx 2018.2. The error message it got was this:

```
ERROR: [SDx-EM 08] Please set XCL_EMULATION_MODE to "hw_emu" to run hardware emulation.
ERROR: [SDx-EM 09] Please set XCL_EMULATION_MODE to "sw_emu" to run software emulation.
ERROR: No devices found
Error: no platforms available or OpenCL install broken
```

Solution is to pass through the environment unmodified.